import Hero from '@/components/Frontpage/Hero/Hero';
import TopMatch from '@/components/Frontpage/TopMatche/Topmatch';
import Head from 'next/head';
import React from 'react'
import { enviourment } from 'next.config';
import Contact from '@/components/Contact/contact';
const ContactUs = ({Data})=>{
    return(
        <>
            <Head>
                <title>Pro Football::Contact us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Hero />
            <Contact />
            
        </>
    )
}

export default ContactUs;

const options = {
	method: 'GET',
	headers: {
		'X-RapidAPI-Key': `${enviourment.MYFOOTBALLAPIKEY}`,
		'X-RapidAPI-Host': `${enviourment.url}`
	}
};

export async function getServerSideProps(){
  const responseLatest= await fetch(`https://${enviourment.url}/`, options);
  const Data = await responseLatest.json();
  return{
    props:{
      Data: Data,
    }
  }
}