import Hero from 'components/Frontpage/Hero/Hero'
import LatestMatch from 'components/Frontpage/Latestmatch/LatestMatch'
import TopMatch from 'components/Frontpage/TopMatche/Topmatch';
import { ImageSkeleton, NewGameSkeleton } from 'components/Skeletons/Skeleton';
import Head from 'next/head'
import { useEffect, useState } from 'react';


// const inter = Inter({ subsets: ['latin'] })

export default function Home({Data}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <LatestMatch Data={Data} />
      <TopMatch  Data={Data} />
    </>
  )
}
const options = {
	method: 'GET',
	headers: {
		'X-RapidAPI-Key': '9e21a3cee8mshf98cb345da11a90p17846bjsnff4266b5ca3e',
		'X-RapidAPI-Host': 'free-football-soccer-videos.p.rapidapi.com'
	}
};

export async function getServerSideProps(){
  const responseLatest= await fetch(`https://free-football-soccer-videos.p.rapidapi.com/`, options);
  const Data = await responseLatest.json();
  return{
    props:{
      Data: Data,
    }
  }
}
